spring.application.name=debate-backend


server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/debate_db
spring.datasource.username=mani
spring.datasource.password=mani2141


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379